# Generated by Django 4.2.13 on 2024-06-01 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "username",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="账号",
                    ),
                ),
                ("password", models.CharField(max_length=16, verbose_name="密码")),
            ],
            options={
                "verbose_name": "学生",
                "verbose_name_plural": "学生",
                "ordering": ["username"],
            },
        ),
        migrations.CreateModel(
            name="TeacherUser",
            fields=[
                (
                    "username",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="users.user",
                    ),
                ),
                ("password", models.CharField(max_length=16, verbose_name="密码")),
            ],
            options={
                "verbose_name": "老师",
                "verbose_name_plural": "老师",
                "ordering": ["username"],
            },
        ),
    ]
