# Generated by Django 4.2.13 on 2024-06-01 22:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stu_page", "0002_alter_showscore_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="showscore",
            table="showscore2",
        ),
    ]
