# Generated by Django 4.2.13 on 2024-06-02 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stu_page", "0003_alter_showscore_table"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Class",
            new_name="Class0",
        ),
    ]
