# Generated by Django 4.2.13 on 2024-06-01 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShowScoreWithClass",
            fields=[
                ("stu_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64)),
                ("score1", models.SmallIntegerField(null=True)),
                ("score2", models.SmallIntegerField(null=True)),
                ("score3", models.SmallIntegerField(null=True)),
                ("class_id", models.SmallIntegerField()),
            ],
            options={
                "db_table": "showscorewithclass",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "teacher_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="users.teacheruser",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
            ],
        ),
    ]
