# Generated by Django 4.2.13 on 2024-06-01 22:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teacher_page", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="showscorewithclass",
            options={"managed": False},
        ),
    ]
